### ISSUE TITLE
Remove notifications button while extension is active

### ISSUE THREAD

**Issue by Riklik101** [yt-focus/yt-focus#12]
**Is your feature request related to a problem? Please describe.**
I noticed that while using the extension I could still click on the notification button, showing multiple videos unrelated to the task at hand and making me get a bit more distracted.

**Describe the solution you'd like**
Removal of said notification icon while the extension is active

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by neezacoto** [comment]
That's a good idea, I have it removed on the homepage but not on other pages. I'll look into it

**Comment by neezacoto** [comment]
Finally got around to it, it should be in the next update
